general:
  collectTelemetryData: false
  verbose: true
steps:
  gctsDeploy:
    host: 'https://gprd.sapds.ru:44300'
    client: '500'
    abapCredentialsId: 'WRGCTS21_4'
    repository: 'EspiUsik-WRGCTS21_4'
  gctsExecuteABAPUnitTests:
    host: 'https://gprd.sapds.ru:44300'
    client: '500'
    abapCredentialsId: 'WRGCTS21_4'
    repository: 'EspiUsik-WRGCTS21_4'
  gctsRollback:
    host: 'https://gprd.sapds.ru:44300'
    client: '500'
    abapCredentialsId: 'WRGCTS21_4'
    repository: 'EspiUsik-WRGCTS21_4'
  abapEnvironmentRunATCCheck:
    abapCredentialsId: 'WRGCTS21_0'
    host: 'gprd.sapds.ru:44300'
    atcConfig: 'atcconfig.yml'
    dockerPullImage: false
